project:
  type: website

website:
  title: "Christian Million"
  site-url: "https://christianmillion.com"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: https://blog.christianmillion.com
        text: Blog
  search:
    location: navbar
    type: textbox

format:
  html:
    theme:
        light: pulse
        dark: solar
    css: styles.css
    toc: true



