project:
  type: website

website:
  favicon: img/favicon.ico
  title: "Christian Million"
  site-url: "https://christianmillion.com"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Blog
      - href: resume.qmd
        text: Resume
    right:
      - icon: envelope
        href: mailto:christianmillion93@gmail.com
      - icon: github
        href: https://github.com/christian-million
      - icon: linkedin
        href: https://www.linkedin.com/in/christianmillion/
      - icon: stack-overflow
        href: https://stackoverflow.com/users/9017311/christian-million?tab=profile
  search:
    location: navbar
    type: overlay

format:
  html:
    theme:
        light: pulse
        dark: solar
    css: styles.css
    toc: true



