---
title: CIM 2019 Prep
author: Christian Million
date: '2019-07-08'
slug: cim-2019-prep
categories:
  - running
tags:
  - running
  - r
subtitle: ''
summary: ''
authors: []
lastmod: '2019-07-08T18:56:06-07:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

In just a few weeks, on August 5th 2019, I will begin training for the 2019 California International Marathon ([CIM](https://runsra.org/california-international-marathon/)). The marathon will be held on December 8th, 2019. I will be following Hal Higdon's 18-week [Intermediate 2 Marathon Training Program](https://www.halhigdon.com/training-programs/marathon-training/intermediate-2-marathon/).

Currently, my goal time for this marathon is 03:30:00 (8:00 min/mile). Though, halfway through the training, I am going to reevaluate my goal time, in order to set realistic expectations. My previous marathon time was [03:58:15](https://www.athlinks.com/event/3241/results/Event/695349/Course/1133196/Bib/7698). Because my new goal is ~ 30 minute faster than my previous time, my training is going to have to be intense. Focus, heart, and dedication will be necessary for this batch of training.

# Reflection on CIM 2018 Training

Last year, I had three goals for CIM:

 - &#10003; Finish!

 - &#10003; Finish under 04:00:00
 
 - &#10007; Finish under 03:45:00 
 
I felt very good about my 3:58:15 time.  I acheived two out of my three goals and I was only 13 minutes under my goal time. Also, because it was my first marathon, I was just happy to finish.

### The Positives

During last years training, there were a few key components to my training that I think helped get so close to my goal:

 - Patience and Understanding
 
 - Awareness during runs
 
 - Solid Weekday runs
 
 - Friends to run with and motivate ([Columbia College Running Ramblers](https://www.facebook.com/pg/ccrunningramblers/posts/)).
 
 - Support from loved ones.
 
 - Tracking the positives and areas for improvements during each run.

I was patient with myself and focused on awareness during my runs. Because it was my first marathon, I cut myself a lot of slack when I felt that even the training runs were too tough. After my first 15 mile long run, all subsequent long runs were the longest runs of my life. I was breaking Strava PR's like crazy. It was important to keep that in perspective during my training. A gentle reminder to myself that it was *supposed* to be hard helped a lot.

### Areas of Improvement

Training was tough, but as always, I could have tried harder. In general, I could improve with:

 - Dedicated strength training.
    - Before 2018, I had never trained physically for anything. I had loosely followed a couple of strength training programs, but those only lasted a few weeks and progress was fleeting. Running is the only exercise I had ever engaged in and enjoyed. Late December of 2018, I began with a personal training at a local personal training facility, ([The Iron Compound](https://www.facebook.com/TheIronCompound/)), in order to better develop general strength and complement my running off-season. 
 
 - Pre-run warm-ups.
    - Actual training runs take a long time, especially when maintaining a full-time job (and a 3 hour commute at the time), so it was hard to justify spending quality time warming up before each run. It doesn't take much, though, and will make it easier to acheive my target goal in 2019.
 
 
 - Post-run recovery (Stretches / Foam Rolling / Meals).
    - Until 2019, I had never taken post-run recovery seriously, which meant it was harder run the next day. My perspective on the importance of recover changed when I first executed a proper recovery routine after a half-marathon, and felt perfect the next day. This time around, post-run recovery will be a must.
 
 
 - Better meal planning.
    - While I always consumed enough calories, those calories were not always from sources conducive to running. This time around, focusing more on high-quality calories (and macro distribution) will help give me the energy needed.
 
 
 - More sleep.
    - A 3 hour daily commute, full work day, long training runs, and prepping food left me little time to socialize. As such, I would sacrifice sleep in order to have some downtime. Sleep is supposed to be one of the most important things for recovery, though. If I want to do better this year, sleep will have to be a priority. 
 
 
 - Morning runs (Instead of evening runs).
    - Might as well train for race conditions. Plus, running after a long day (even on the weekends) is harder to get excited about.
 
 
 - Take ALL long runs seriously.
    - There were two important long runs during last year's training for which I was either hungover or sleep-deprived. These were not fun runs. I imagine they may have detracted from my overall performance on race day, too.


# Planning for CIM 2019

With a little more planning this year, I can take out some of the cognitive costs of training. This year, my planning will include methods to tackle the areas of improvement above.

### Timeline

 - August 5th, 2019: First Official Training Run
 
 - October 6th, 2019: [Urban Cow Half-Marathon](https://www.urbancowhalf.com/) (Half-way through training)
 
 - December 8th, 2019: Race Day!


### Preparation

Over the next few weeks, I am hoping to acheive the following:

 - [ ] Refine and outline warm-up and recovery routines
 
 - [ ] Create process to view training progress against training plan.
 
 - [ ] Outline meal plan / macro distributions
 
 - [ ] Purchase and break in some race day shoes.
 
I'm also hoping to use this training journey as an opportunity to practice using R, exploratory data analysis, and develop better writing skills.